menuItems/urls.py
from django.conf.urls import url

from .views import (
    MenuItemListView,
    MenuItemDetailView,
    MenuItemCreateView,
    MenuItemUpdateView,
    MenuItemDetailUpdateView
)

urlpatterns = [
    url(r'^$', MenuItemListView.as_view(), name='list'),
    url(r'^create/$', MenuItemCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/update/$', MenuItemUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/$', MenuItemDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', MenuItemDetailUpdateView.as_view(), name='detail'),
]

profiles/urls.py
from django.conf.urls import url

from .views import ProfileDetailVeiw, UnfollowProfileView, FollowProfileView,ToggleFollowProfileView

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailVeiw.as_view(), name='detail'),
    url(r'^unfollow/(?P<username>[\w-]+)/$', UnfollowProfileView.as_view(), name='unfollow'),
    url(r'^follow/(?P<username>[\w-]+)/$', FollowProfileView.as_view(), name='follow'),
    url(r'^toggle-follow/(?P<username>[\w-]+)/$', ToggleFollowProfileView.as_view(), name='toggle-follow'),
]

trydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView

from django.views.generic import TemplateView
from menuItems.views import HomeView
from profiles.views import RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate-user'),
    url(r'^login/$', LoginView.as_view(), name='login_url'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': '/registration/login.html/'}, name='logout_url'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^menu-items/', include('menuItems.urls', namespace='menuItems')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
]

menuItems/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save

from trydjango.utils import unique_slug_generator
from restaurants.models import Restaurant

class MenuItem(models.Model):
    # relationship fields
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(Restaurant)
    # menuItem fields
    name        = models.CharField(max_length=120)
    contents    = models.TextField(help_text='Separate each item by comma')
    excludes    = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    public      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menuItems:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

def menuItem_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(menuItem_pre_save_receiver, sender=MenuItem)

menuItems/forms.py
from django import forms
from .models import MenuItem
from restaurants.models import Restaurant

class MenuItemCreateForm(forms.Form):
    # menuItem fields
    restaurant  = forms.IntegerField(required=True)
    name        = forms.CharField(required=True)
    contents    = forms.CharField()
    excludes    = forms.CharField()
    public      = forms.BooleanField()

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name=='No Restaurant':
            raise forms.ValidationError("Not a valid Restaurant Name")
        return name

class MenuItemCreateModelForm(forms.ModelForm):

    class Meta:
        model = MenuItem
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(MenuItemCreateModelForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = Restaurant.objects.filter(owner=user)#, menuitem__isnull=True)#.exclude(menuitem__isnull=False)

    def clean_name(self):
        name = self.cleaned_data.get('name')

        if name == 'No Restaurant':
            raise forms.ValidationError('Not a valid Restaurant Name')

        return name

menuItems/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView

from .models import MenuItem
from .forms import MenuItemCreateModelForm

class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, "home.html", {})

        user = request.user
        following_user_ids = [x.id for x in user.profile.following.all()]
        qs = MenuItem.objects.filter(user__id__in=following_user_ids, public=True).order_by("-updated")
        return render(request, "menuItems/home-feed.html", {'qs': qs})

class MenuItemListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        queryset = MenuItem.objects.filter(user=self.request.user)
        return queryset

class MenuItemDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return MenuItem.objects.filter(user=self.request.user)

class MenuItemCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = MenuItemCreateModelForm
    template_name = 'forms.html'
    success_message = "Menu item created successfully!"

    def form_valid(self, form):
        menuItem = form.save(commit=False)

        menuItem.user = self.request.user

        return super(MenuItemCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(MenuItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Menu Item'
        return context

    def get_form_kwargs(self, **kwargs):
        kwargs = super(MenuItemCreateView, self).get_form_kwargs(**kwargs)
        kwargs['user'] = self.request.user
        return kwargs


class MenuItemUpdateView(LoginRequiredMixin, UpdateView):
    form_class = MenuItemCreateModelForm
    template_name = 'forms.html'

    def get_queryset(self):
        return MenuItem.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(MenuItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Menu Item: {}'.format(self.get_object().name)
        return context

    def get_form_kwargs(self, **kwargs):
        kwargs = super(MenuItemUpdateView, self).get_form_kwargs(**kwargs)
        kwargs['user'] = self.request.user
        return kwargs

class MenuItemDetailUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = MenuItemCreateModelForm
    template_name = 'menuItems/detail-update.html'
    success_message = "Menu item updated successfully!"

    def get_queryset(self):
        return MenuItem.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(MenuItemDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Menu Item: {}'.format(self.get_object().name)
        return context

    def get_form_kwargs(self, **kwargs):
        kwargs = super(MenuItemDetailUpdateView, self).get_form_kwargs(**kwargs)
        kwargs['user'] = self.request.user
        return kwargs

templates/menuItems/detail-update.html
{% extends 'base.html' %}
{% block title %}
    <title>{{form.instance.name}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
    <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">

        <h4>Item Name: {{ form.instance }}</h4>
        <br>Added by: {{ form.instance.user }}<br>
        Restaurant Name: {{ form.instance.restaurant }}<br>
        {% if form.instance.contents %}
            Contents: <br>
            <ul>
                {% for content in form.instance.get_contents %}
                    <span class="badge badge-default">{{ content }}</span>
                {% endfor %}
            </ul>
        {% endif %}

        {% if form.instance.excludes %}
            Excludes: <br>
            <ul>
                {% for exclude in form.instance.get_excludes %}
                    <span class="badge badge-default">{{ exclude }}</span>
                {% endfor %}
            </ul>
        {% endif %}
        Added Date: {{ form.instance.timestamp }}<br>
        Updated Date: {{ form.instance.updated }}
        </div>
    </div>
    </div>

<hr/>

<h3>Make Changes</h3>
    {% include 'snippets/form-snippet.html' with form=form %}
{% endblock content %}

templates/menuItems/form.html
{% extends 'base.html' %}
{% block title %}
    <title>{{ title }}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>{{ title }}</h1>
    {% if form.erros.non_field_errors %}
        {{ form.errors.non_field_errors }}
    {% endif %}
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock content %}

templates/menuItems/home-feed.html
{% extends 'base.html' %}
{% block title %}
    <title>Menu Items List</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>Menu Item List of your Followers</h1>
<ul>
    {% for obj in qs %}
    <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">

        <h4>Item Name: <a href="{% url 'profiles:detail' username=obj.user %}?q={{ obj }}">{{ obj }}</a></h4>
        <br>Added by: <a href="{% url 'profiles:detail' username=obj.user %}?q={{ obj.user }}">{{ obj.user }}</a><br>
        Restaurant Name: <a href="{% url 'profiles:detail' username=obj.user %}?q={{ obj.restaurant }}">{{ obj.restaurant }}</a><br>
        {% if obj.contents %}
            <ul>
            Contents: <br>

                {% for content in obj.get_contents %}
                    <a href="{% url 'profiles:detail' username=obj.user %}?q={{ content }}"><span class="badge badge-default">{{ content }}</span></a>
                {% endfor %}
            </ul>
        {% endif %}

        {% if obj.excludes %}
            <ul>
            Excludes: <br>
                {% for exclude in obj.get_excludes %}
                    <span class="badge badge-default">{{ exclude }}</span>
                {% endfor %}
            </ul>
        {% endif %}
        Added Date: {{ obj.timestamp }}<br>
        Updated Date: {{ obj.updated }}
        </div>
    </div>
    </div>

    {% empty %}
        <li><a href="{% url 'menuItems:create' %}">Add a Menu Item</a></li>
    {% endfor %}
</ul>
{% endblock content %}

templates/menuItems/menuitem_detail.html
{% extends 'base.html' %}
{% block title %}
    <title>{{object.name}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
    <h1>{{ object }}</h1>
{#        <a href="{{ obj.slug }}">{{ obj }}</a>#}
        <br>Added by: {{ object.user }}<br>
        Restaurant Name: {{ object.restaurant }}<br>
        {% if object.contents %}
            Contents: <br>
            <ul>
                {% for content in object.get_contents %}
                    <li>{{ content }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if object.excludes %}
            Excludes: <br>
            <ul>
                {% for exclude in object.get_excludes %}
                    <li>{{ exclude }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        Added Date: {{ object.timestamp }}<br>
        Updated Date: {{ object.updated }}
{% endblock content %}

templates/menuItems/menuitem_list.html
{% extends 'base.html' %}
{% block title %}
    <title>Menu Items</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>Menu Item List <samll><a href="{% url 'menuItems:create' %}">Add</a></samll></h1>
<ul>
    {% for obj in object_list %}
    <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">

        <h4>Item Name: <a href="{{ obj.get_absolute_url }}">{{ obj }}</a></h4>
        <br>Added by: {{ obj.user }}<br>
        Restaurant Name: {{ obj.restaurant }}<br>
        {% if obj.contents %}
            <ul>
            Contents: <br>

                {% for content in obj.get_contents %}
                    <span class="badge badge-default">{{ content }}</span>
                {% endfor %}
            </ul>
        {% endif %}

        {% if obj.excludes %}
            <ul>
            Excludes: <br>
                {% for exclude in obj.get_excludes %}
                    <span class="badge badge-default">{{ exclude }}</span>
                {% endfor %}
            </ul>
        {% endif %}
        Added Date: {{ obj.timestamp }}<br>
        Updated Date: {{ obj.updated }}
        </div>
    </div>
    </div>

    {% empty %}
        <li><a href="{% url 'menuItems:create' %}">Add a Menu Item</a></li>
    {% endfor %}
</ul>
{% endblock content %}