profiles/urls.py
from django.conf.urls import url

from .views import ProfileDetailVeiw, UnfollowProfileView, FollowProfileView,ToggleFollowProfileView

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailVeiw.as_view(), name='detail'),
    url(r'^unfollow/(?P<username>[\w-]+)/$', UnfollowProfileView.as_view(), name='unfollow'),
    url(r'^follow/(?P<username>[\w-]+)/$', FollowProfileView.as_view(), name='follow'),
    url(r'^toggle-follow/(?P<username>[\w-]+)/$', ToggleFollowProfileView.as_view(), name='toggle-follow'),
]

trydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView

from django.views.generic import TemplateView
from menuItems.views import HomeView
from profiles.views import RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate-user'),
    url(r'^login/$', LoginView.as_view(), name='login_url'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': '/registration/login.html/'}, name='logout_url'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^menu-items/', include('menuItems.urls', namespace='menuItems')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
]

menuItems/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save

from trydjango.utils import unique_slug_generator
from restaurants.models import Restaurant

class MenuItem(models.Model):
    # relationship fields
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(Restaurant)
    # menuItem fields
    name        = models.CharField(max_length=120)
    contents    = models.TextField(help_text='Separate each item by comma')
    excludes    = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    public      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('menuItems:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

def menuItem_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(menuItem_pre_save_receiver, sender=MenuItem)

profiles/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from .utils import code_generator

User = settings.AUTH_USER_MODEL

class ProfileManager(models.Manager):

    def following_list(self, request_user):
        return request_user.profile.following.all()

    def followers_list(self, request_user):
        user_model = get_user_model()

        followers_list = user_model.objects.filter(profile__following=request_user)
        return followers_list

    def suggested_list(self, request_user):

        following_list = self.following_list(request_user)
        suggested_list = []
        for fellow in following_list:
            fellow_s_following_list = fellow.profile.following.all()
            for item in fellow_s_following_list:
                if item not in suggested_list and item not in following_list and item != request_user:
                    suggested_list.append(item)

        followers_list = self.followers_list(request_user)

        for fellow in followers_list:
            if fellow not in following_list and fellow not in suggested_list and fellow != request_user:
                suggested_list.append(fellow)
        return suggested_list

    def toggle_follow(self, request_user, username_to_toggle):
        following_list = request_user.profile.following.all()

        user_to_toggle = Profile.objects.get(user__username__exact=username_to_toggle).user
        is_following = False
        if user_to_toggle in following_list:
            request_user.profile.following.remove(user_to_toggle)
        else:
            request_user.profile.following.add(user_to_toggle)
            is_following = True

        return is_following

class Profile(models.Model):
    user        = models.OneToOneField(User) #user.profile accesses profile and reverse
    following   = models.ManyToManyField(User, related_name='followers', blank=True)
    activation_key = models.CharField(max_length=120, blank=True, null=True)
    activated   = models.BooleanField(default=False)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    def __str__(self):
        return self.user.username

    def send_activate_email(self):
        if not self.activated:
            self.activation_key = code_generator()
            self.save()

            subject = 'Activate User Email'
            from_email = settings.DEFAULT_FROM_EMAIL
            message = "Active your email here: ".format(self.activation_key)
            recipient_list = [self.user.email]
            html_message = 'Active your email here: {}'.format(self.activation_key)
            print(html_message)
            send_mail = False

            path_ = reverse('activate-user', kwargs={"code": self.activation_key})
            html_message = 'Active your email here: {}'.format(path_)
            print(html_message)

            # sent_mail = send_mail(
            #                         subject,
            #                         message,
            #                         from_email,
            #                         recipient_list,
            #                         fail_silently=False,
            #                         html_message=html_message
            #                     )
            return send_mail

def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)
        the_super_user_profile = Profile.objects.get_or_create(user__id=1)[0]
        profile.following.add(the_super_user_profile.user)
        the_super_user_profile.following.add(instance)

post_save.connect(post_save_user_receiver, sender=User)

restaurants/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save, post_save
from trydjango.utils import unique_slug_generator
from .validators import validate_caterogy

User = settings.AUTH_USER_MODEL

# Create your models here.
class RestaurantQuerySet(models.query.QuerySet):
    def search(self, query):#Restaurant.objects.all().search(query) or Restaurant.objects.filter(something).search()
        if query:
            query = query.strip()
            return self.filter(
                Q(owner__username=query) |
                Q(name__icontains=query) |
                Q(location__icontains=query) |
                Q(category__icontains=query) |
                Q(menuitem__name__icontains=query) |
                Q(menuitem__contents__icontains=query)
            ).distinct()
        else:
            return self

class RestaurantManager(models.Manager):
    def get_queryset(self):
        return RestaurantQuerySet(self.model, using=self._db)

    def search(self, query):#Restaurant.objects.search()
        return self.get_queryset().search(query)

class Restaurant(models.Model):
    owner            = models.ForeignKey(User)
            #class_instance.model_name_set.all() = restaurants
            # and     model.owner_id gives id of user
            # and     model.owner gives user
    name            = models.CharField(max_length=100)
    location        = models.CharField(max_length=255, null=True, blank=True)
    category        = models.CharField(max_length=255, null=True, blank=True, validators=[validate_caterogy])
    timestamp       = models.DateTimeField(auto_now_add=True)   # Saves automatically and does not allow to make changes
    updated         = models.DateTimeField(auto_now=True)       # Saves automatically and does not allow to make changes
    slug            = models.SlugField(null=True, blank=True)
    # my_date_field   = models.DateTime(auto_now=False, auto_now_add=False)

    objects = RestaurantManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return '/restaurants/{}'.format(self.slug)
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name


def r_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.category = instance.category.capitalize()
    print ('saving..')
    print (instance.timestamp)
    if not instance.slug:               #always do pre_save
        instance.slug = unique_slug_generator(instance)

# def r_post_save_receiver(sender, instance, *args, **kwargs):
#     print ('saved..')
#     print (instance.timestamp)
#     # instance.save()                     #not a recommanded way to save because it will run into an infinite loop as save() will recall post_save()
#     if not instance.slug:                 #this will never be called because the presave will already set the instance.slug, so infinite loop will be avoided
#         instance.slug = unique_slug_generator(instance)
#         instance.save()

pre_save.connect(r_pre_save_receiver, sender=Restaurant)
# post_save.connect(r_post_save_receiver, sender=Restaurant)

profiles/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError("Email already exists")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        # create a new user hash for activating email.

        if commit:
            user.save()
            user.profile.send_activate_email()
        return user

profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import View, DetailView, CreateView
from restaurants.models import Restaurant
from menuItems.models import MenuItem
from .models import Profile
from .forms import RegisterForm

User = get_user_model()

def activate_user_view(request, code=None, *args, **kwargs):
    if code:
        profile_qs = Profile.objects.filter(activation_key=code)
        if profile_qs.exists() and profile_qs.count() == 1:
            profile = profile_qs.first()
            if not profile.activated:

                user_ = profile.user
                user_.is_active = True
                user_.save()
                profile.activated = True
                profile.activation_key = None
                profile.save()
                return redirect("/login/")
    return redirect("/login/")

class RegisterView(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = '/'
    success_message = "Your account was created successfully!"

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return redirect('/login/')
        return super(RegisterView,self).dispatch(*args,**kwargs)

class ProfileDetailVeiw(LoginRequiredMixin, DetailView):
    template_name = 'profiles/user_detail.html'
    
    def get_object(self):
        username = self.kwargs.get('username')
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailVeiw, self).get_context_data(*args, **kwargs)
        user = context['user']
        query = self.request.GET.get('q')

        restaurant_qs = Restaurant.objects.filter(owner=user).search(query)

        context['following'] = Profile.objects.following_list(user)
        context['suggested'] = Profile.objects.suggested_list(user)
        context['followers'] = Profile.objects.followers_list(user)

        request_user = self.request.user
        request_user_following_list = []

        if user != self.request.user:
            request_user_following_list = request_user.profile.following.all()

        is_following = False
        if user in request_user_following_list:
            is_following = True

        context['is_following'] = is_following

        menuItem_qs = MenuItem.objects.filter(user=user).exists()

        if restaurant_qs.exists() and menuItem_qs:
            context['restaurants'] = restaurant_qs

        return context

class UnfollowProfileView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = request.user
        username = self.kwargs.get('username')
        user_to_unfollow = User.objects.get(username__exact=username)

        user.profile.following.remove(user_to_unfollow)

        return redirect("/profiles/{}/".format(user))

class FollowProfileView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = request.user
        username = self.kwargs.get('username')
        user_to_follow = User.objects.get(username__exact=username)

        user.profile.following.add(user_to_follow)

        return redirect("/profiles/{}/".format(user))

class ToggleFollowProfileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = request.user
        username = self.kwargs.get('username')

        toggle_follow = Profile.objects.toggle_follow(user, username)

        return redirect("/profiles/{}/".format(username))

profiles/templates/profiles/user_detail.html
{% extends 'base.html' %}
{% block title %}
    <title>{{user.username}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
    {% if user != request.user %}
        {% include 'profiles/snippets/follow_form.html' with username=user.username is_following=is_following %}
    {% endif %}
    <h1>{{user.username}}</h1>
    <hr/>
    <form class="form" method="GET" action=".">
        <input type="text" placeholder="Search.." name="q" value="{{ request.GET.q }}">
        <button class="btn btn-default" type="submit">Search</button>
    </form>

    {% if following %}
        {% if user == request.user %}
            <h3>You are following</h3>
        {% else %}
            <h3>{{ user.username }} is following</h3>
        {% endif %}
        <ul>
            <div class="row">
            {% for fellow in following %}
                <div class="col-sm-4">
                    <div class="thumbnail">
                        <a href="{% url 'profiles:detail' username=fellow.username %}">{{ fellow }}</a>
                        {% if user == request.user %}
                        <a href="{% url 'profiles:unfollow' username=fellow.username %}" class="pull-right">
                            <span class="badge badge-default">Unfollow</span>
                        </a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
        </ul>
    {% endif %}

    {% if suggested %}
        {% if user == request.user %}
            <h3>You may follow</h3>
        {% else %}
            <h3>{{ user.username }} may follow</h3>
        {% endif %}
        <ul>
            <div class="row">
            {% for fellow in suggested %}
                <div class="col-sm-4">
                    <div class="thumbnail">
                        <a href="{% url 'profiles:detail' username=fellow.username %}">{{ fellow }}</a>
                        {% if user == request.user %}
                        <a href="{% url 'profiles:follow' username=fellow.username %}" class="pull-right">
                            <span class="badge badge-default">Follow</span>
                        </a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
        </ul>
    {% endif %}

    {% if followers %}
        {% if user == request.user %}
            <h3>Your Followers</h3>
        {% else %}
            <h3>{{ user.username }}'s Followers</h3>
        {% endif %}
        <ul>
            <div class="row">
            {% for fellow in followers %}
                <div class="col-sm-4">
                    <div class="thumbnail">
                        <a href="{% url 'profiles:detail' username=fellow.username %}">{{ fellow }}</a>
{#                        {% if user == request.user %}#}
{#                        <a href="{% url 'profiles:follow' username=fellow.username %}" class="pull-right">#}
{#                            <span class="badge badge-default">Follow</span>#}
{#                        </a>#}
{#                        {% endif %}#}
                    </div>
                </div>
            {% endfor %}
            </div>
        </ul>
    {% endif %}

    {% if restaurants %}
        {% if user == request.user %}
            <h3>Your Restaurant List</h3>
        {% else %}
            <h3>{{ user.username }}'s Restaurant List</h3>
        {% endif %}
        <ul>
        {% for rest in restaurants %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                    <h3>{{ rest }}</h3>
                    <p><a href="{{ request.path }}?q={{ rest.location }}">{{ rest.location }}</a> | <a href="{{ request.path }}?q={{ rest.category }}">{{ rest.category }}</a></p>
                    {% if rest.menuitem_set.all.exists %}
                    <h3>Menu Items:</h3>
                    <ul>
                        {% for item in rest.menuitem_set.all %}
                            <li><h3><a href="{{ request.path }}?q={{ item }}">{{ item }}</a></h3><br>
                                {% if item.contents %}
                                    <ul>
                                    Contents: <br>

                                        {% for content in item.get_contents %}
                                            <a href="{{ request.path }}?q={{ content }}"><span class="badge badge-default">{{ content }}</span></a>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                                {% if item.excludes %}
                                    <ul>
                                    Excludes: <br>
                                        {% for exclude in item.get_excludes %}
                                            <span class="badge badge-default">{{ exclude }}</span>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p class="lead">No items found</p>
                    {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </ul>
    {% else %}
    <p class="lead">No restaurants found</p>
    {% endif %}
{% endblock content %}

profiles/templates/profiles/user_detail_up_to_chap_39.html
{% extends 'base.html' %}
{% block title %}
    <title>{{user.username}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
    <h1>{{user.username}}</h1>
    <hr/>

    {% if user.restaurant_set.all.exists %}
            <h3>{{user.username}}'s Restaurants</h3>
        <ul>
        {% for rest in user.restaurant_set.all %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                    <h3>{{ rest }}</h3>
                    <p>{{ rest.location }} | {{ rest.category }}</p>
                    {% if rest.menuitem_set.all.exists %}
                    <h3>Menu Items:</h3>
                    <ul>
                        {% for item in rest.menuitem_set.all %}
                            <li><h3>{{ item }}</h3><br>
                                {% if item.contents %}
                                    <ul>
                                    Contents: <br>

                                        {% for content in item.get_contents %}
                                            <span class="badge badge-default">{{ content }}</span>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                                {% if item.excludes %}
                                    <ul>
                                    Excludes: <br>
                                        {% for exclude in item.get_excludes %}
                                            <span class="badge badge-default">{{ exclude }}</span>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                        <p class="lead">No items found</p>
                    {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </ul>
    {% else %}
    <p class="lead">No restaurants found</p>
    {% endif %}
{% endblock content %}