profiles/urls.py
from django.conf.urls import url

from .views import ProfileDetailVeiw, UnfollowProfileView, FollowProfileView,ToggleFollowProfileView

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailVeiw.as_view(), name='detail'),
    url(r'^unfollow/(?P<username>[\w-]+)/$', UnfollowProfileView.as_view(), name='unfollow'),
    url(r'^follow/(?P<username>[\w-]+)/$', FollowProfileView.as_view(), name='follow'),
    url(r'^toggle-follow/(?P<username>[\w-]+)/$', ToggleFollowProfileView.as_view(), name='toggle-follow'),
]

restaurants/urls.py
from django.conf.urls import url

from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView,
    RestaurantDetailUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/update/$', RestaurantUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantDetailUpdateView.as_view(), name='detail'),
]

trydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView

from django.views.generic import TemplateView
from menuItems.views import HomeView
from profiles.views import RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate-user'),
    url(r'^login/$', LoginView.as_view(), name='login_url'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': '/registration/login.html/'}, name='logout_url'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^menu-items/', include('menuItems.urls', namespace='menuItems')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
]

templates/snippets/css.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

templates/snippets/form-snippet.html
{% if form.erros.non_field_errors %}
    {{ form.errors.non_field_errors }}
{% endif %}
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class="container">
    <nav class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse" style="padding:0px !important;">
            <ul class="nav navbar-nav">
                <li class="active">
                  <a href="{% url 'home' %}">Home</a>
                </li>
                <li>
                  <a href="{% url 'contact' %}">Contact</a>
                </li>
                <li>
                  <a href="{% url 'about' %}">About</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'restaurants:list' %}">Restaurants</a>
                    </li>
                    <li>
                        <a href="{% url 'menuItems:list' %}">Menu Items</a>
                    </li>
                    <li>
                        <a href="{% url 'profiles:detail' username=request.user.username%}">My Profile</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right" style="padding-right: 15px;">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout_url' %}?next=/login/">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login_url' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/snippets/sidebar.html
<ul>
    <li>item 1</li>
    <li>item 2</li>
    <li>item 3</li>
    <li>item 4</li>
</ul>