profiles/urls.py
from django.conf.urls import url

from .views import ProfileDetailVeiw, UnfollowProfileView, FollowProfileView,ToggleFollowProfileView

urlpatterns = [
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailVeiw.as_view(), name='detail'),
    url(r'^unfollow/(?P<username>[\w-]+)/$', UnfollowProfileView.as_view(), name='unfollow'),
    url(r'^follow/(?P<username>[\w-]+)/$', FollowProfileView.as_view(), name='follow'),
    url(r'^toggle-follow/(?P<username>[\w-]+)/$', ToggleFollowProfileView.as_view(), name='toggle-follow'),
]

restaurants/urls.py
from django.conf.urls import url

from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView,
    RestaurantDetailUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/update/$', RestaurantUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantDetailUpdateView.as_view(), name='detail'),
]

trydjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordResetView, LogoutView

from django.views.generic import TemplateView
from menuItems.views import HomeView
from profiles.views import RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate-user'),
    url(r'^login/$', LoginView.as_view(), name='login_url'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': '/registration/login.html/'}, name='logout_url'),
    url(r'^password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^menu-items/', include('menuItems.urls', namespace='menuItems')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
]

restaurants/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save, post_save
from trydjango.utils import unique_slug_generator
from .validators import validate_caterogy

User = settings.AUTH_USER_MODEL

# Create your models here.
class RestaurantQuerySet(models.query.QuerySet):
    def search(self, query):#Restaurant.objects.all().search(query) or Restaurant.objects.filter(something).search()
        if query:
            query = query.strip()
            return self.filter(
                Q(owner__username=query) |
                Q(name__icontains=query) |
                Q(location__icontains=query) |
                Q(category__icontains=query) |
                Q(menuitem__name__icontains=query) |
                Q(menuitem__contents__icontains=query)
            ).distinct()
        else:
            return self

class RestaurantManager(models.Manager):
    def get_queryset(self):
        return RestaurantQuerySet(self.model, using=self._db)

    def search(self, query):#Restaurant.objects.search()
        return self.get_queryset().search(query)

class Restaurant(models.Model):
    owner            = models.ForeignKey(User)
            #class_instance.model_name_set.all() = restaurants
            # and     model.owner_id gives id of user
            # and     model.owner gives user
    name            = models.CharField(max_length=100)
    location        = models.CharField(max_length=255, null=True, blank=True)
    category        = models.CharField(max_length=255, null=True, blank=True, validators=[validate_caterogy])
    timestamp       = models.DateTimeField(auto_now_add=True)   # Saves automatically and does not allow to make changes
    updated         = models.DateTimeField(auto_now=True)       # Saves automatically and does not allow to make changes
    slug            = models.SlugField(null=True, blank=True)
    # my_date_field   = models.DateTime(auto_now=False, auto_now_add=False)

    objects = RestaurantManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return '/restaurants/{}'.format(self.slug)
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name


def r_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.category = instance.category.capitalize()
    print ('saving..')
    print (instance.timestamp)
    if not instance.slug:               #always do pre_save
        instance.slug = unique_slug_generator(instance)

# def r_post_save_receiver(sender, instance, *args, **kwargs):
#     print ('saved..')
#     print (instance.timestamp)
#     # instance.save()                     #not a recommanded way to save because it will run into an infinite loop as save() will recall post_save()
#     if not instance.slug:                 #this will never be called because the presave will already set the instance.slug, so infinite loop will be avoided
#         instance.slug = unique_slug_generator(instance)
#         instance.save()

pre_save.connect(r_pre_save_receiver, sender=Restaurant)
# post_save.connect(r_post_save_receiver, sender=Restaurant)

restaurants/forms.py
from django import forms
from .models import Restaurant
from .validators import validate_caterogy, validate_email

class RestaurantCreateForm(forms.Form):
    name = forms.CharField()
    location = forms.CharField(required=False)
    category = forms.CharField(required=True)

    def clean_name(self):
        name = self.cleaned_data.get("name");
        if name=="hellow":
            raise forms.ValidationError("Not a Valid Name")
        return name

class RestaurantCreateModelForm(forms.ModelForm):
    # email = forms.EmailField()
    # if v validator added to model field itself in models.py then the followin line is not needed
        # category = forms.CharField(required=False, validators=[validate_caterogy])
    class Meta:
        model = Restaurant
        fields = [
            'name',
            'location',
            'category'
        ]

    def clean_name(self):
        name = self.cleaned_data.get("name");
        if name=="hellow":
            raise forms.ValidationError("Not a Valid Name")
        return name

    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     if ".edu" in email:
    #         raise forms.ValidationError("Invalid Email");
    #     return email

restaurants/views.py
import random
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from .forms import RestaurantCreateForm, RestaurantCreateModelForm

from .models import Restaurant

class RestaurantListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)

class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)

class RestaurantCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = RestaurantCreateModelForm
    template_name = 'forms.html'
    # success_url = '/restaurants/'
#         Chapter 25. The Extra Power of Django Model Forms
    success_message = "Restaurant created successfully!"

    def form_valid(self, form):
        restaurant = form.save(commit=False)

        restaurant.owner = self.request.user
        #         when not logged in the self.request.user gives the class AnonymousUser not the User that we want
        # restaurant.save()
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = "Add Restaurant"
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantCreateModelForm
    template_name = 'forms.html'

    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Restaurant: {}'.format(self.get_object().name)
        return context

class RestaurantDetailUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = RestaurantCreateModelForm
    template_name = 'restaurants/detail-update.html'
    success_message = "Restaurant updated successfully!"

    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Restaurant: {}'.format(self.get_object().name)
        return context

templates/restaurants/detail-update.html
{% extends 'base.html' %}
{% block title %}
    <title>{{form.instance.title}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
    <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
        <h4><h1>{{form.instance.title}}</h1></h4>
        <br>{{ form.instance.location }} - {{ form.instance.category }} - {{ form.instance.timestamp }} - {{ form.instance.updated }}
        </div>
    </div>
    </div>

<hr/>

<h3>Make Changes</h3>
    {% include 'snippets/form-snippet.html' with form=form %}
{% endblock content %}

templates/restaurants/form.html
{% extends 'base.html' %}
{% block title %}
    <title>{{ title }}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>{{ title }}</h1>
{#    Receiving validaiton of RestaurantCreateView #}
    {% if form.erros.non_field_errors %}
        {{ form.errors.non_field_errors }}
    {% endif %}
{#    Receiving validaiton of RestaurantCreateView #}

{#    Receiving validaiton of restaurant_create_modal_view and restaurant_create_view #}
    {#    {% if erros %}#}
    {#        {{ errors }}#}
    {#    {% endif %}#}
{#    Receiving validaiton of restaurant_create_modal_view and restaurant_create_view #}
<form method="POST"> {% csrf_token %}
{#    <input type="text" name="title" placeholder="Your Title"><br/><br/>#}
{#    <input type="text" name="location" placeholder="Your Location"><br/><br/>#}
{#    <input type="text" name="category" placeholder="Your Category"><br/><br/>#}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock content %}

templates/restaurants/restaurant_detail.html
{% extends 'base.html' %}
{% block title %}
    <title>{{object.name}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>{{object.title}}</h1>
<ul>
    <li>{{ object.location }} - {{ object.category }} - {{ object.timestamp }} - {{ object.updated }}</li>
</ul>
{% endblock content %}

templates/restaurants/restaurant_list.html
{% extends 'base.html' %}
{% block title %}
    <title>Restaurants</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>My Restaurants <samll><a href="{% url 'restaurants:create' %}">Add</a></samll></h1>
<ul>
    {% for obj in object_list %}
    <div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
        <h4><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></h4>
        <br>{{ obj.location }} - {{ obj.category }} - {{ obj.timestamp }} - {{ obj.updated }}
        </div>
    </div>
    </div>

    {% empty %}
        <li><a href="{% url 'restaurants:create' %}">Add a Restaurant</a></li>
    {% endfor %}
</ul>
{% endblock content %}

templates/restaurants/restaurant_view.html
{% extends 'base.html' %}
{% block title %}
    <title>{{obj_list.title}}</title>
{% endblock title %}

{% block head %}
    {{ block.super }}
{% endblock head %}

{% block content %}
<h1>Restaurant List</h1>
<ul>
    {% for obj in obj_list.restaurants %}
    <li>{{ obj }}<br>{{ obj.name }} - {{ obj.location }} - {{ obj.category }} - {{ obj.timestamp }} - {{ obj.updated }}</li>
    {% endfor %}
</ul>
{% endblock content %}